# Generated by Django 5.0 on 2025-09-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlisting',
            name='location',
            field=models.CharField(choices=[('Nav', 'Nav Apartments'), ('Willage', 'Willage'), ('Woodruff', 'Woodruff'), ('Brittain', 'Brittain'), ('Scheller', 'Scheller Courtyard')], max_length=20),
        ),
    ]

# Generated by Django 5.0 on 2025-09-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlisting',
            name='location',
            field=models.CharField(choices=[('Nav', 'Nav Apartments'), ('Willage', 'Willage'), ('Woodruff', 'Woodruff'), ('Brittain', 'Brittain'), ('Scheller', 'Scheller Courtyard')], max_length=20),
        ),
    ]
